import type { DemoTourDefinition } from './types';

export const dentalDemoTour: DemoTourDefinition = {
  id: 'dentalcare-sales',
  storageKey: 'dentalcare.demo-tour',
  intro: {
    title: 'Кабинет стоматологической клиники',
    lead: 'Это живой продукт, не слайдшоу. Пройдём путь пациента: план лечения, зубная карта, запись на этап и возврат в admin.',
    bullets: [
      'Анна Смирнова — 2 из 5 этапов уже выполнены',
      'Запись привязана к этапу плана, а не к абстрактной услуге',
      'Tour сам ничего не записывает и не завершает визит',
    ],
    startLabel: 'Начать демо',
    skipLabel: 'Смотреть самостоятельно',
  },
  finish: {
    title: 'Дальше — операционный контур',
    lead: 'В admin можно завершить визит: этап плана станет completed, прогресс пересчитается, следующий этап останется доступен.',
    bullets: [
      'Unscheduled treatment показывает стоимость незаписанных этапов',
      'Write-операции защищены ADMIN_TOKEN',
      '/demo/admin остаётся только для чтения',
    ],
    adminLabel: 'Открыть admin',
    continueLabel: 'Остаться в кабинете',
  },
  steps: [
    {
      id: 'home',
      target: 'next-visit',
      route: '/',
      title: 'Кабинет пациента',
      description: 'Не каталог услуг: ближайший визит, врач, кабинет и статус.',
    },
    {
      id: 'plan-home',
      target: 'plan-summary',
      route: '/',
      title: 'План лечения',
      description: '2 из 5 этапов завершено, 74 000 ₽ по плану, 28 000 уже оплачено.',
    },
    {
      id: 'chart',
      target: 'dental-chart',
      route: '/chart',
      title: 'Зубная карта',
      description: 'Постоянные зубы по FDI. Цвет показывает статус — от здорового до «нужно лечить».',
    },
    {
      id: 'tooth-16',
      target: 'tooth-16',
      route: '/chart',
      title: 'Зуб 16',
      description: 'Кариес уже в плане лечения. Нажмите на зуб, чтобы увидеть процедуру и стоимость.',
    },
    {
      id: 'drawer',
      target: 'tooth-drawer',
      route: '/chart',
      title: 'Карточка зуба',
      description: 'Проблема, рекомендуемая процедура и CTA на запись — без автоматического диагноза.',
    },
    {
      id: 'item',
      target: 'plan-item-scheduled',
      route: '/plan',
      title: 'Этап плана',
      description: 'Лечение зуба 16 уже scheduled. Следующий этап 26 ждёт записи.',
    },
    {
      id: 'book',
      target: 'plan-item-planned',
      route: '/plan',
      title: 'Запись на этап',
      description: 'Кнопка «Записаться» ведёт в слоты с сохранённым treatment item. Tour сам запись не создаёт.',
    },
    {
      id: 'slots',
      target: 'book-slots',
      route: '/book?itemId=4',
      title: 'Свободные слоты',
      description: 'Backend учитывает врача, кабинет и блоки. Frontend не назначает resource сам.',
      waitMs: 4000,
    },
    {
      id: 'confirm',
      target: 'book-confirm',
      route: '/book?itemId=4',
      title: 'Подтверждение',
      description: 'После явного подтверждения этап станет scheduled, а визит появится на главном экране.',
      waitMs: 4000,
    },
    {
      id: 'home-after',
      target: 'next-visit',
      route: '/',
      title: 'Визит на главной',
      description: 'Ближайший приём остаётся в кабинете: перенос и отмена — здесь.',
    },
    {
      id: 'admin',
      target: 'admin-dashboard',
      route: '/demo/admin',
      title: 'Admin dashboard',
      description: 'Сегодняшние визиты, выручка, планы в работе и recall due.',
      waitMs: 3500,
    },
    {
      id: 'complete',
      target: 'admin-appointments',
      route: '/demo/admin?tab=appointments',
      title: 'Complete visit',
      description: 'Write-complete доступен в /admin с токеном. Здесь только просмотр: tour ничего не меняет.',
      waitMs: 3500,
    },
    {
      id: 'progress',
      target: 'plan-timeline',
      route: '/plan',
      title: 'Прогресс плана',
      description: 'После complete этапа 16 прогресс станет 3 из 5, зуб 26 останется planned.',
    },
    {
      id: 'unscheduled',
      target: 'unscheduled-kpi',
      route: '/demo/admin?tab=unscheduled',
      title: 'Unscheduled treatment',
      description: '386 000 ₽ этапов без записи — главный коммерческий сигнал клиники.',
      waitMs: 3500,
    },
  ],
};
